### PR TITLE
Add documentation for image map content type

### PR DESCRIPTION
**Pull request by luca-rath**
| Q | A
| --- | ---
| Fixed tickets | fixes #issuenum
| Related PRs | sulu/sulu#5434
| License | MIT

#### What's in this PR?

Add documentation for image map content type.

#### Why?

Every content type should be documented.

### CODE REVIEW

**Comment by nnatter** [comment]
can we add a basic twig example here?

**Comment by luca-rath** [comment]
@nnatter Would it be enough to just link here? https://github.com/sulu/sulu/blob/master/templates/pages/includes/image_map.html.twig

**Comment by nnatter** [comment]
I dont have a strong opinion 🙂  What do you think? @alexander-schranz

**Comment by luca-rath** [comment]
Because this is not a "simple" example, I would prefer that to not bloat the documentation

**Comment by luca-rath** [comment]
but it's still the most minimal I could think of

**Comment by luca-rath** [comment]
@alexander-schranz whats your opinion on this?

**Comment by alexander-schranz** [comment]
@luca-rath then its more important as we have an example in the example.html.twig you could just copy that into this file.

**Comment by luca-rath** [comment]
@alexander-schranz I'm sorry, I think I don't know exactly what you mean now 🙂 Should I copy just the link to the example or the whole example itself?

**Comment by alexander-schranz** [comment]
@luca-rath whole twig example code.

**Comment by luca-rath** [comment]
@alexander-schranz changed it

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@luca-rath awesome. Thank yoU!

**Pull request merged**
