### PR TITLE
Fix github urls after rename of organization

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| License | MIT

#### What's in this PR?

Fix all github.com/sulu-io urls to github.com/sulu

#### Why?

The github organization was renamed

### CODE REVIEW

**Comment by wachterjohannes** [comment]
hmm i think we have to merge master into develop before merging this.

**Comment by wachterjohannes** [comment]
and should also be merged into master

**Comment by wachterjohannes** [comment]
@alexander-schranz could you create a PR for master? then i could merge it in there and then merge master into develop.

**Comment by alexander-schranz** [comment]
@wachterjohannes #216

**Comment by wachterjohannes** [comment]
thanks

**Pull request closed without merging**
