### PR TITLE
Add some extra info for the single_media_selection contentType

### PR DESCRIPTION
**Pull request by eekes**
The single_media_selection contentType was missing in the 'Creating a Page Template' page, also added links to the return value.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@eekes Thank you for your Pull Request can you rebase your branch for the 2.0 release branch?

**Comment by danrot** [comment]
I think I would not mention the `Media` object as you did it... Can we just remove these parts? The problem with this GitHub link, is that it potentially will link to the wrong version of the file once we release new versions.

**Comment by eekes** [comment]
> I think I would not mention the `Media` object as you did it... Can we just remove these parts? The problem with this GitHub link, is that it potentially will link to the wrong version of the file once we release new versions.

@danrot Ok will do. The reason I did that was because I saw these pages were linking to the return types too:

https://docs.sulu.io/en/2.0/reference/content-types/single_contact_selection.html
https://docs.sulu.io/en/2.0/reference/content-types/single_account_selection.html

**Comment by danrot** [comment]
That's interesting... But well, then you can leave it as it is :slightly_smiling_face: Have to think how to handle this on a more generic level in that case.

**Comment by danrot** [comment]
But this still contains too many commits, can you change that? :slightly_smiling_face:

**Comment by eekes** [comment]
@danrot I think it should be OK now... Thanks again @alexander-schranz for the rebasing info/help! Never did that before.

**Comment by danrot** [comment]
Thank you very much for this contribution! :tada:

**Pull request merged**
