### PR TITLE
Update set permission for installation

### PR DESCRIPTION
**Pull request by alexander-schranz**
Inspired by Symfony: http://symfony.com/doc/2.8/book/installation.html#book-installation-permissions

### CODE REVIEW

**Comment by danrot** [comment]
The mac osx variant works, will test the linux command later before merging.

**Comment by danrot** [comment]
@alexander-schranz If you are already touching this stuff, can you also integrate the suggested change in https://github.com/sulu-io/sulu/pull/2001#issuecomment-183361824 ?

**Comment by alexander-schranz** [comment]
would set the `/uploads/media` also set to `/uploads` so a developer can create their his own folders to store files what you think @danrot

**Comment by danrot** [comment]
That's what we have agreed on in the other discussion, no?

**Comment by alexander-schranz** [comment]
notsure, but if this is ok branch is rebased an ready to merge.

**Comment by patkar** [comment]
Btw. #166 already changed `/uploads/media` to `/media` too on the develop ;)

**Comment by danrot** [comment]
True, but then it looks like this branch was created before that.

**Pull request merged**
