### PR TITLE
Add hint to remove routes manually

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Fixed tickets | none
| License | MIT

#### What's in this PR?

Contains a hint to remove routes manually.

### CODE REVIEW

**Comment by danrot** [comment]
Is this handled by the bundle automatically, if it is used in combination with a `RoutableEntity`? And has this been introduced in Sulu 2.0, or did it already exist before that release?

**Comment by wachterjohannes** [comment]
@danrot this depends on https://github.com/sulu/sulu/pull/4914 which is not merged until now and it will go to 2.1 - until then we should keep this open.

**Comment by danrot** [comment]
Then it should not go into the 2.0 branch I guess :slightly_smiling_face:

**Comment by wachterjohannes** [comment]
@danrot @alexander-schranz fixed and ready to review again

**Pull request merged**
